In [4]:
import numpy as np

In [5]:
my_list = [1,2,3]

In [7]:
array = np.array(my_list)

In [8]:
array

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
matrix = np.array(my_matrix)

In [13]:
matrix #2d-array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,10) #start from 0, goes up to but no including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(5) #1D array of 0s

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,5)) #2D array of 0s, need to pass in a tuple (row, col)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.linspace(0,20,10) #returns 1D array of 10 evenly spaced numbers between 0 and 20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [30]:
np.eye(5) #create Identity matrix, remember need to be a square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(5) #create a 1D array of 5 values, populated by random samples from a UNIFORM distribution from 0 to 1

array([0.34152068, 0.76016201, 0.70644594, 0.42272506, 0.49852047])

In [34]:
np.random.rand(5,3) #2D version of above, note that we DON'T pass in a tuple

array([[0.79683105, 0.32206623, 0.87777496],
       [0.10238389, 0.5540067 , 0.42993123],
       [0.65701428, 0.26695816, 0.60751278],
       [0.34134801, 0.06325853, 0.96005332],
       [0.07344669, 0.04929659, 0.68927887]])

In [35]:
np.random.randn(5) #1D array of 5 values, random samples from Normal distribution centered around 0

array([-0.02744802,  3.41882209, -0.01015889,  1.417626  ,  1.27744215])

In [49]:
np.random.randint(1,100,10) #10 numbers [1,100), default if size field not set, gives 1 number

array([68, 14, 92, 73, 19, 44,  5, 16, 30, 18])

In [51]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
rand_arr = np.random.randint(0,50,10)
rand_arr

array([35, 49, 14,  1, 31, 18, 49, 20, 42,  2])

In [54]:
#reshape array: 
#Total size of new array must be unchanged, i.e. arr has 25 elements, we can reshape to 5x5, but not 5x10
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
rand_arr.max() #max value of the array

49

In [57]:
rand_arr.min()

1

In [58]:
#find locations of max or min value
rand_arr.argmax() #this returns the index value of the location of the maximum value. only returns the first one.

1

In [59]:
rand_arr.argmin()

3

In [61]:
arr.shape #shape of arr array to find size

(25,)

In [63]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [65]:
arr.dtype #returns the data type of the stuff in the array

dtype('int64')

In [72]:
from numpy.random import randint
randint(0,10) #after import, don't need to call numpy.random in front of it anymore

8